AllCops:
  NewCops: enable

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc
  IgnoredMethods:
    # Gemfile
    - group
    # Rake
    - namespace
    - task
    # RSpec
    - before
    - context
    - describe
    - it

Metrics/MethodLength:
  Max: 25
