language: ruby
cache: bundler
before_script:
  - echo 'true' > audio_command.txt
  - echo 'true' > speech_command.txt
script:
  - bundle exec rspec
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
